### PR TITLE
normalize json format

### PR DESCRIPTION
**Pull request by kalw**
Normalize post data json content with double quote when single quote are present.

### CODE REVIEW

**Comment by kalw** [comment]
credits trayez

**Comment by tobli** [comment]
Hi @kalw!
Could you please explain the background for this PR. Are you experiencing a problem that you want to solve? I don't understand why you're changing the data that's posted. E.g. {"text": "abc'def"} would be changed to {"text": "abc\"def"}

/Tobias

**Comment by kalw** [comment]
Hi @tobli !

You're totally right, I've tried quickly -too quickly- to solve a HAR parsing issue where some json resource present are "badly" formated like {'text': 'abc"def'}.

Let me find a proper way to lint it.


--
Regis A. Despres

**Comment by tobli** [comment]
Ok, thanks. Do you have an example of a Chrome log that generates an invalid har?

**Comment by tobli** [comment]
I'm closing this PR now, but please open a new issue if you find an example of an invalid generated HAR file.

**Pull request closed without merging**
