### PR TITLE
Add an option to include requestId as _request_id in the HAR

### PR DESCRIPTION
**Pull request by mnmkng**
Hi @soulgalore 

I've prepared the PR @jancurn suggested in https://github.com/sitespeedio/chrome-har/issues/24

Its a simple change, but I've added a test anyway. Feel free to comment.

Cheers!

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @mnmkng great! I'll have a look and merge tonight. There were two eslint errors on Travis can you fix them? You can run `npm lint:fix` and push the change + add a ignore for the console log.

One last thing, do you use Chrome-HAR standalone or through Browsertime (is a new release of Chrome-HAR enough or do you need BT too?). 

Best
Peter

**Comment by tobli** [comment]
Hi @mnmkng, thanks for contributing. Please see my comment here: 
https://github.com/sitespeedio/chrome-har/issues/24#issuecomment-405541814. I'd prefer removing the preference, and just naming the property _request_id in the first place. Note however the added 'r'.

**Comment by mnmkng** [comment]
@tobli @soulgalore Thank you for the comments guys! Could @soulgalore please confirm that @tobli 's way is the way to go? I would update the PR.

**Comment by soulgalore** [comment]
Yes please do :)

**Comment by soulgalore** [comment]
Ah cool. @tobli do you have time to look before merge?

Hmm yes, I wonder though if it isn't Puppeteer that handles it wrong, so there's a way to configure it differently? We use the trace log enabled with page/network Selenium/Chromedriver style, you can check it [here](https://github.com/sitespeedio/browsertime/blob/master/lib/chrome/webdriver/index.js#L82).

**Comment by tobli** [comment]
Looking closer into what WPT does I'm not sure this is correct. For redirects WPT adds a "-1", "-2" etc. suffix in the _request_id field, rather than just a "r". Need to check in more detail, but I suspect that long redirect chains doesn't work correctly with our current approach. WPT uses the "_raw_id" extension field for the original request id in a long chain. For an example, check [this HAR](https://www.webpagetest.org/export.php?bodies=1&pretty=1&test=180719_6F_4125e6d6d69c5ffd58637f359eab7269) from [this test](
https://www.webpagetest.org/result/180719_6F_4125e6d6d69c5ffd58637f359eab7269/).

I'd like us to add more tests for long redirect chains before locking down this in public api, as it might need to change.

**Comment by jancurn** [comment]
Hey guys, it would be great if we could get the Puppeteer request ID to the HAR in any shape or form. Currently this is a showstopper for us as there is no correct way to attach the raw content of the HTTP requests to the resulting HAR file. The only other way for us to move forward is to fork this repo and republish it on NPM...

**Comment by soulgalore** [comment]
@jancurn yeah sorry. Both me and @tobli is on vacation see https://github.com/sitespeedio/sitespeed.io#vacation-july---august and @beenanner is at Next '18. 

@tobli is the creator of the project so I wanna make sure things get the way he wants.

**Comment by jancurn** [comment]
I understand. Many thanks for your help guys!

**Pull request closed without merging**
